### PR TITLE
Better syn highlight

### LINKED ISSUE #5: Could be simpler
I need to re-think and refactor the colors and definitions

### PR DESCRIPTION
**Pull request by ThatXliner**
Optimized` _base.less` Closes #5 #3

### CODE REVIEW

**Comment by ThatXliner** [comment]
@KomodoKode I want to discuss about the red

useful links:
https://coolors.co/fa7b7b-fa7687-f97092
https://coolors.co/fa7d7d-f9798a-f87593 (lightened and desaturated)

**Comment by KomodoKode** [comment]
I feel like its too pink-ish. What about #F63C55 or #F75066?

**Comment by ThatXliner** [comment]
#F75066 Looks OK but the colors aren't harmonized

**Comment by ThatXliner** [comment]
Screen Shot 2021-01-02 at 1 05 31 PM
Actually, what do you think?

**Comment by ThatXliner** [comment]
Screen Shot 2021-01-02 at 1 06 05 PM
Your new red gives off a different vibe

**Comment by KomodoKode** [comment]
You have a point...

The red should probably be darker. Thinking of C7283D.

**Comment by KomodoKode** [comment]
> Screen Shot 2021-01-02 at 1 05 31 PM
> 
> Actually, what do you think?

This looks ok though many of the colors look very similar.

**Comment by KomodoKode** [comment]
Maybe too pink? I mean its fall syntax after all. Try #d6294b
Screen Shot 2021-01-03 at 7 32 00 AM
 or a darker #c21f3f.
Screen Shot 2021-01-03 at 7 31 40 AM

**Comment by ThatXliner** [comment]
Those colors does [horribly on coolor's contrast checker](https://coolors.co/contrast-checker/d6294b-1e1c21)

The pink ones, on the other hand [does decently well](https://coolors.co/contrast-checker/f87593-1e1c21)

**Comment by KomodoKode** [comment]
I see. If "very good" is ok with you, then I think #FF8787 might be the best color for this theme.

**Review by KomodoKode — COMMENTED** [review]
New color pallette looks good, pull request should be merged.

**Pull request merged**
