### PR TITLE
Added Sublime text port to port list

### PR DESCRIPTION
**Pull request by imnotril**
Added my Sublime text port, love ur color scheme <33

### CODE REVIEW

**Comment by ThatXliner** [comment]
Glad you’re liking it!

**Comment by ThatXliner** [comment]
@imnotril even though I’ve merged it for now, I would like a few suggestIons

1. I don’t use Sublime Text anymore but I do remember there being a package manager. I wonder if you are able to submit the package to package control https://packagecontrol.io/docs/submitting_a_package
2. The punctuation in your port is white (although I suppose that’s a limitation of the theming in Sublime Text)

**Comment by imnotril** [comment]
I have been making changes to the color scheme to publish it in the package manager and I wanted to know, `@mono-2` is the punctuation color?

**Comment by imnotril** [comment]
@ThatXliner The package is in the process of being published into package control.

Although it needs to be checked, you can see the [pr](https://github.com/wbond/package_control_channel/pull/8639).

**Comment by ThatXliner** [comment]
> `@mono-2` is the punctuation color?

yes it is

**Comment by imnotril** [comment]
> 1. I don’t use Sublime Text anymore but I do remember there being a package manager. I wonder if you are able to submit the package to package control https://packagecontrol.io/docs/submitting_a_package

Done, although it may take some time for the color scheme to be published in the package manager. 

> 2. The punctuation in your port is white (although I suppose that’s a limitation of the theming in Sublime Text)

Done, even though some symbols fail because they are considered `meta.*` and not `punctuation.*`. Although there are very few symbols I could try to fix it in the future, but I think I'll leave it like this for now because I have to learn more about sublime text scopes.

**Pull request merged**
