### PR TITLE
Finalize

### LINKED ISSUE #14: Better support for color blindness

### LINKED ISSUE #21: Recalibrate colors with HSB
See [this blog](https://howlettstudios.com/articles/2017/5/6/the-problem-with-hsv)

### PR DESCRIPTION
**Pull request by ThatXliner**
Closes #21 
closes #14

### CODE REVIEW

**Comment by ThatXliner** [comment]
@KomodoKode Please review (and test for color-blindess support)

**Review by KomodoKode — APPROVED** [review]
Minor edits reviewed without any problems.

Color blindness support looks fine.

**Comment by KomodoKode** [comment]
Contrast between red/orange could be better though.

**Comment by ThatXliner** [comment]
> Contrast between red/orange could be better though.

Light orange or the orange? @KomodoKode

**Pull request merged**
